data-module: experiment.qa.data.insuranceqa.tsv
model-module: experiment.qa_pairwise.model.coala_pmeans
training-module: experiment.qa_pairwise.train.training
evaluation-module: experiment.qa_pairwise.evaluation.evaluation

logger:
  level: DEBUG
  path: logs/se_travel_coala_pmeans.txt

global: 
  question_length: 50
  answer_length: 400
  embedding_size: 300

data:
  lowercased: false
  map_oov: true
  map_numbers: false
  embeddings_path: ../glove.840B.300d.txt
  add_coref: true

  train_data:
    - data/stackexchange-answerselection/travel.stackexchange.com

model:
  filters: 850
  window_size: 2
  trainable_embeddings: false
  n_p_values: 72

training:
  n_train_answers: 50
  save_folder: checkpoints/se_travel_pmean
  remove_save_folder_on_start: false
  epochs: 100
  early_stopping_patience: 10
  dropout: 0.1

  optimizer: adam
  initial_learning_rate: 0.0001
  dynamic_learning_rate: false

  batchsize: 40
  batchsize_valid: 500

evaluation:
  skip: false
  output: '../'
