data-module: experiment.qa.data.insuranceqa.tsv
model-module: experiment.qa_hinge.model.attention_lstm
training-module: experiment.qa_hinge.train.training
evaluation-module: experiment.qa_hinge.evaluation.evaluation

logger:
  level: DEBUG
  path: logs/se_travel_attention_lstm.txt

global: 
  question_length: 50
  answer_length: 400
  embedding_size: 300

data:
  lowercased: false
  map_oov: true
  map_numbers: false
  embeddings_path: ../glove.840B.300d.txt
  add_coref: true

  train_data:
    - data/stackexchange-answerselection/travel.stackexchange.com

model:
  lstm_cell_size: 370
  trainable_embeddings: false
  margin: 0.1

training:
  n_train_answers: 50
  save_folder: checkpoints/se_travel_attention_lstm
  remove_save_folder_on_start: false
  epochs: 100
  early_stopping_patience: 10
  dropout: 0.45

  optimizer: adam
  initial_learning_rate: 0.0051
  dynamic_learning_rate: false

  batchsize: 90
  batchsize_valid: 500

evaluation:
  skip: false
  output: '../'
